apiVersion: apps/v1
kind: Deployment
metadata:
  name: exam-deployment
spec:
  selector:
    matchLabels:
      run: exam-deployment
  replicas: 1
  template:
    metadata:
      labels:
        run: exam-deployment
    spec:
      containers:
      - name: exam-deployment
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 8000

        