name: DAST
'on':
  # push:
  #   branches:
  #     - GCP-DEV
  # pull_request:
  #   branches:
  #     - GCP-DEV
  # workflow_dispatch: null
  workflow_run:
    workflows: ["Build and Deploy to GKE"]
    branches: 
      - GCP-DEV
      - master
    types: 
      - completed
  workflow_dispatch: null   
  





jobs:
   DAST_Zap:
    name: DAST Zap
    runs-on: ubuntu-latest 
    steps:
     - name: zap-Scan
       uses: zaproxy/action-full-scan@v0.2.0
       with:
        target: ${{ secrets.EXT_IP }}
     - name: artifacts
       uses: actions/upload-artifact@v2
       with:
          name: DAST-artifact
          path: ${{ github.workspace }}
          
