name: DAST with OWASP ZAP
on:
  # push:
  #   branches:
  #     - GCP-DEV
  # pull_request:
  #   branches:
  #     - GCP-DEV
  # workflow_dispatch: null
  workflow_run:
    workflows: ["Run Selenium Tests"]
    types: 
      - completed
  workflow_dispatch: null   
  





jobs:
   DAST:
    name: DAST Zap
    runs-on: ubuntu-latest 
    steps:
     - name: zap-Scan
       uses: zaproxy/action-full-scan@v0.3.0
       with:
        target: ${{ secrets.EXT_IP }}
     - name: artifacts
       uses: actions/upload-artifact@v2
       with:
          name: DAST-artifact
          path: ${{ github.workspace }}
          
