name: Run Selenium Tests
on:
  workflow_run:
    workflows: ["Test-Pipeline"]
    branches: [GCP-DEV]
    types: 
      - completed
  workflow_dispatch: null    

#  push:
#    branches:
#      - GCP-DEV
#  pull_request:
#    branches:
#      - GCP-DEV
  # workflow_dispatch: null

env:
    target_url: "${{ secrets.EXT_IP }}"
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest selenium
      - name: Run tests with pytest
        run: pytest  --capture=no --verbose test_selenium.py